### ISSUE TITLE
import baidu-map in NgModule

### ISSUE THREAD

**Issue by kuangYIN1217** [cipchk/angular-baidu-maps#1]
AbmModule.forRoot({apiKey: 'bLf1IX78tWQ8tBzu6m5GvnbxSsxLYWNA' // app key为必选项 })
error:Argument type {apiKey: string} is not assignable to parameter type AbmConfig
![bu 4m e wdp04u5 da j a](https://user-images.githubusercontent.com/27177389/33602297-df308ffe-d9e9-11e7-8fbd-4d16309f8f3c.png)

**Comment by cipchk** [comment]
我不确定是什么原因，先尝试重新安装包体。
