### ISSUE TITLE
请问如何使用 BMapLib ?

### ISSUE THREAD

**Issue by limthengwai** [cipchk/angular-baidu-maps#11]
我们尝试使用点聚合工具 MarkerClusterer,  但是得到  ERROR ReferenceError: BMapLib is not defined. 怀疑是没引进一些 library. 请问有人尝试过用点聚合工具么？ 请多多指教 

谢谢 :)

**Comment by cipchk** [comment]
应该是需要额外引入 `https://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js` 文件的吧，目前的确不支持，但是你可以试着在 `index.html` 中加入这个引用，但未必可行，我会在下一版本中增加可以额外引用这种文件的相关代码 。

**Comment by limthengwai** [comment]
> 应该是需要额外引入 `https://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js` 文件的吧，目前的确不支持，但是你可以试着在 `index.html` 中加入这个引用，但未必可行，我会在下一版本中增加可以额外引用这种文件的相关代码 。

好的，谢谢。 我尝试在 angular.json 里 引用， 暂时可行。 但还是期待着您的下个版本 :)
