### ISSUE TITLE
地图的销毁

### ISSUE THREAD

**Issue by joseph830727** [cipchk/angular-baidu-maps#15]
百度地图原生的js api中map对象有个destroy的方法，来销毁地图，但是，
onReady(map){
        this._map = map;
        map.addControl(new BMap.MapTypeControl());
        map.enableScrollWheelZoom(true);
        this.initView();
    }
初始化地图，然后调用this._map.destroy();确提示destroy is not a function，请问还有什么销毁方法吗？
还是，组件自己有销毁地图的操作，不需要显示条用销毁操作？

**Comment by cipchk** [comment]
[destroy](https://mapopen-pub-jsapi.bj.bcebos.com/jsapi/reference/jsapi_webgl_1_0.html) 是存在的；没有重现示例无法分析 。不过可以从：

- 百度地图版本是不是最新
- 是不是 dom 已经移除了，然后才调用 `destroy` 方法的。

**Comment by joseph830727** [comment]
感谢回复，我重新写了一个可以复现的demo，具体如下：
demo有两个组件，一个是map的，一个是其他的，两个组件通过路由来回切换，从map切换到其他的时候，我在map最近的ngOnDestroy方法里面，调用了this._map.destroy();，就会提示ERROR Error: Uncaught (in promise): TypeError: this._map.destroy is not a function，请帮忙看看，但是，调用AbmComponent的destroy()方法是可以的，但是，我看代码里面只是清除了一些地图上的覆盖物，没有销毁地图实例，请帮忙查看，附加demo下载地址[https://pan.baidu.com/s/1YVgOfUKoLiD-J6E7b1BKKw](url) 提取码：fqw3

**Comment by joseph830727** [comment]
找到问题了，百度地图的3.0 api没有destroy() 这个方法，提供这个方法的是gl 1.0版本
