### ISSUE TITLE
getting "您需要申请全景地图服务使用权限" error

### ISSUE THREAD

**Issue by smallvalthoss** [cipchk/angular-baidu-maps#16]
Hello, I am getting an error that says I need permission to use the panoramic map service?

**Comment by cipchk** [comment]
You need to apply for permission at [Baidu panorama](https://lbsyun.baidu.com/index.php?title=jspopular3.0/guide/panorama).

**Comment by smallvalthoss** [comment]
thanks, looks like i need to be chinese to get it working...
