### ISSUE TITLE
onReady 运行时间

### ISSUE THREAD

**Issue by xingkoo** [cipchk/angular-baidu-maps#2]
偶尔会出现没有执行onReady的情况，需要重新刷新页面。
不知道这个方法是何种情况加载的。

**Comment by cipchk** [comment]
观察一下是否正确加载百度 JavaScript 类库？

**Comment by xingkoo** [comment]
检查加载了多次，有可能是热更新导致的。等我晚点上传到服务器上后，观察下开发版会不会存在多次打开导致多次加载的情况后汇报上来。

**Comment by xingkoo** [comment]
已确认是热更新导致的重复加载类库总是.
