### ISSUE TITLE
map.addEventListener() 事件并没有绑定

### ISSUE THREAD

**Issue by wxyer** [cipchk/angular-baidu-maps#3]
map.addEventListener('click', (e: any) => {
      this.messageService.add(e.target.getLabel() + ' ProjectMarker has been clicked!');
    });

 this._map.addEventListener('click', this.PickUpInfo.bind(this));
两种方法都尝试了，点击地图并没有进入事件回调函数。
请教下，原因可能是什么

**Comment by cipchk** [comment]
map 对象确保是通过 `(ready)="onReady($event)"` 获得的。
